export const ChainList = {
  Mainnet: { id: 1, name: 'Mainnet', symbol: 'eth' },
  Ropsten: { id: 3, name: 'Ropsten', symbol: 'eth' },
  Rinkeby: { id: 4, name: 'Rinkeby', symbol: 'eth' },
  Goerli: { id: 5, name: 'Goerli', symbol: 'eth' },
  BinanceSmartChain: { id: 56, name: 'Binance Smart Chain', symbol: 'bnb' },
  BinanceSmartChainTestnet: {
    id: 97,
    name: 'Binance Smart Chain Testnet',
    symbol: 'bnb',
  },
  HuobiEcoChain: { id: 128, name: 'Huobi ECO Chain', symbol: 'HT' },
  MaticNetwork: { id: 137, name: 'Matic Network', symbol: 'MATIC' },
  Harmony: { id: 1666600000, name: 'Harmony', symbol: 'ONE' },
  HarmonyTestnet: { id: 1666700000, name: 'Harmony Testnet', symbol: 'ONE' },
  FantomOpera: { id: 250, name: 'Fantom Opera', symbol: 'FTM' },
  PolygonMumbaiTestnet: {
    id: 4002,
    name: 'Polygon Mumbai Testnet',
    symbol: 'MATIC',
  },
  MaticMumbaiTestnet: {
    id: 80001,
    name: 'Matic Mumbai Testnet',
    symbol: 'MATIC',
  },
  XdaiChain: { id: 100, name: 'xDAI Chain', symbol: 'xDAI' },
  Moonbeam: { id: 1287, name: 'Moonbeam', symbol: 'GLMR' },
  Avalanche: { id: 43114, name: 'Avalanche', symbol: 'AVAX' },
  FujiTestnet: { id: 43113, name: 'Fuji Testnet', symbol: 'AVAX' },
  FeiProtocol: { id: 1666, name: 'Fei Protocol', symbol: 'FEI' },
  LineaSepolia: { id: 59141, name: 'Linea Sepolia', symbol: 'lineaSepolia' },
};
